// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRm3wHFFfWHrJxd_wfD7veegLCiqGQiYE',
    appId: '1:1033615784985:web:f8cc579b30286120f8fe88',
    messagingSenderId: '1033615784985',
    projectId: 'chat-app-flutter-146d9',
    authDomain: 'chat-app-flutter-146d9.firebaseapp.com',
    storageBucket: 'chat-app-flutter-146d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBDz9RjsH6wpNLqFFg_NvQUtAitmhAnz8',
    appId: '1:1033615784985:android:dae55f7883df3c25f8fe88',
    messagingSenderId: '1033615784985',
    projectId: 'chat-app-flutter-146d9',
    storageBucket: 'chat-app-flutter-146d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjuTpYaRGnPVgcUF-yvuQnEDqUH9Amo5Y',
    appId: '1:1033615784985:ios:3fb6fe6f38c88c93f8fe88',
    messagingSenderId: '1033615784985',
    projectId: 'chat-app-flutter-146d9',
    storageBucket: 'chat-app-flutter-146d9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjuTpYaRGnPVgcUF-yvuQnEDqUH9Amo5Y',
    appId: '1:1033615784985:ios:1f179dca7f24b11cf8fe88',
    messagingSenderId: '1033615784985',
    projectId: 'chat-app-flutter-146d9',
    storageBucket: 'chat-app-flutter-146d9.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
